### ISSUE TITLE
Customize UI extension

### ISSUE THREAD

**Issue by mrezauli** [zepfietje/minimal-code#3]
after turning on settings sync Customize UI blocks rebooting VS Code

**Comment by zepfietje** [comment]
Hey, @mrezauli, thanks for opening an issue!

This is a known issue that was caused by a change in VS Code: https://github.com/iocave/customize-ui/issues/156.
You could either reinstall and stick to 1.73.1 or try switching to VSCodium: https://github.com/iocave/customize-ui/issues/156#issuecomment-1411197296.
